In [44]:
import pandas as pd
import numpy as np

# Question 01

In [3]:
pd.__version__

'2.0.3'

In [113]:
url =  'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'

In [114]:
df = pd.read_csv(url)


In [115]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

# Question 02

In [11]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


# Question 3

In [30]:
#Number of columns
df.isnull().sum() #how many missing values are there

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question 4

In [35]:
df.ocean_proximity.nunique()

5

# Question 5

In [20]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

In [27]:
df.groupby('ocean_proximity').median_house_value.mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

# Question 6

In [116]:
mean = df['total_bedrooms'].mean()
mean

537.8705525375618

In [117]:
df['total_bedrooms'].fillna(mean, inplace=True)
print(df['total_bedrooms'].mean())


537.8705525375617


# Question 7

### Select only columns housing_median_age, total_rooms, total_bedrooms.


In [125]:
x = df[['housing_median_age','total_rooms','total_bedrooms']]
x = x.fillna(x.median())

### Get the underlying NumPy array. Let's call it X.


In [126]:
X = x.to_numpy()
X

array([[  41.,  880.,  129.],
       [  21., 7099., 1106.],
       [  52., 1467.,  190.],
       ...,
       [  17., 2254.,  485.],
       [  18., 1860.,  409.],
       [  16., 2785.,  616.]])

In [48]:
### Compute matrix-matrix multiplication between the transpose of X and X.


In [138]:
XT = np.transpose(X)
XT_X = np.dot(XT, X)
XT_X

array([[2.01984850e+07, 1.35332892e+09, 2.83204712e+08],
       [1.35332892e+09, 2.41621366e+11, 4.67660348e+10],
       [2.83204712e+08, 4.67660348e+10, 9.59926544e+09]])

In [49]:
### # Compute the inverse of XTX.


In [128]:
XT_X_inv = np.linalg.inv(XT_X)
XT_X_inv

array([[ 8.47988169e-08,  1.62386103e-10, -3.29291640e-09],
       [ 1.62386103e-10,  7.28537219e-11, -3.59722129e-10],
       [-3.29291640e-09, -3.59722129e-10,  1.95383149e-09]])

In [ ]:
# Create an array y with values [950, 1300, 800, 1000, 1300].


In [136]:
y = np.array([950, 1300, 800, 1000])
y

array([ 950, 1300,  800, 1000])

In [137]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y.
w = np.dot(np.dot(XT_X_inv, XT), y)


ValueError: shapes (3,20640) and (4,) not aligned: 20640 (dim 1) != 4 (dim 0)