In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\eduva\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

# Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
#access element 3

a[2]

3

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimentional arrays

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [26]:
n[0,1]

2

In [27]:
n[1]

array([4, 5, 6])

In [29]:
n[:,1]

array([2, 5, 8])

# Randomly generated arrays

In [35]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [37]:
np.random.seed(2)
np.random.randint(low=0, high= 100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
a + 1

array([1, 2, 3, 4, 5])

In [42]:
b = (10 + (a*2)) ** 2 / 100

In [43]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison operators

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a > 2

array([False, False, False,  True,  True])

In [46]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [47]:
a[a > b]

array([2, 3, 4])

# Summarizing operators

In [48]:
a

array([0, 1, 2, 3, 4])

In [49]:
a.sum()

10