# Linear algebra

In [2]:
import numpy as np

# Vector operations

In [12]:
u = np.array([2,4,5,6])

In [13]:
u

array([2, 4, 5, 6])

In [14]:
v = np.array([1,0,0,2])

In [15]:
u + v

array([3, 4, 5, 8])

# Vector multiplication

In [44]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [45]:
vector_vector_multiplication(u,v)

14.0

In [29]:
u.dot(v)

14

In [24]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

In [25]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [41]:
U.shape

(3, 4)

In [34]:
V = np.array([
    [1,2,2,],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])
    

In [46]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)
    
    return result  

In [47]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [56]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[0]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = U[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
    
    return result

In [57]:
matrix_matrix_multiplication(U,V)

AssertionError: 